In [1]:
import torch
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, hamming_loss
import numpy as np

In [15]:
pred = torch.randint(0,3,(4,5))
label = torch.randint(0,3,(4,5))
print(pred)
print(label)

tensor([[1, 1, 0, 1, 2],
        [2, 0, 1, 2, 1],
        [2, 1, 1, 0, 2],
        [2, 2, 0, 1, 2]])
tensor([[2, 2, 2, 0, 0],
        [0, 1, 0, 1, 2],
        [1, 1, 1, 0, 2],
        [2, 1, 1, 2, 2]])


In [17]:
print(torch.flatten(label))
print(torch.flatten(pred))
print(accuracy_score(torch.flatten(label),torch.flatten(pred)))

tensor([2, 2, 2, 0, 0, 0, 1, 0, 1, 2, 1, 1, 1, 0, 2, 2, 1, 1, 2, 2])
tensor([1, 1, 0, 1, 2, 2, 0, 1, 2, 1, 2, 1, 1, 0, 2, 2, 2, 0, 1, 2])
0.3


In [2]:
def return_two(a):
    return a,a+1

In [4]:
a,b = return_two(3)
print(a)

3
