In [19]:
import dgl
import torch
import numpy as np
import networkx as nx
from dgl.nn import GraphConv

In [3]:
g=nx.complete_graph(5)
g=dgl.from_networkx(g)

In [5]:
feat=torch.randn((5,10))

In [15]:
g.ndata['f']=feat
obj=torch.randint(2,size=(5,))
g.ndata['obj']=obj

In [12]:
print(g.ndata['f'])

tensor([[-0.0359,  0.3321,  0.2561, -1.3504, -0.7434,  0.3317, -1.4431, -0.8261,
          0.0092,  0.9999],
        [-0.7560, -0.5649,  0.3543, -1.0330, -0.5975,  1.8829,  0.0560, -0.9059,
          0.4356, -0.1094],
        [-0.6200, -0.3877, -0.3335,  1.3879,  0.0655,  0.4008, -1.0524,  1.9360,
         -0.8590,  0.0442],
        [ 0.4674,  0.9094, -0.9535,  1.4495, -0.1925,  0.8344, -1.0422,  0.3841,
          1.5234,  1.2190],
        [-1.0471, -0.4344, -1.5509,  2.2143, -0.7519, -1.7530,  0.6610,  0.8409,
          0.5515, -0.6521]])


In [16]:
print(g.ndata['obj'])

tensor([0, 1, 1, 0, 1])


In [18]:
print(torch.nonzero(g.ndata['obj']).squeeze())

tensor([1, 2, 4])


In [24]:
conv=GraphConv(10,20)

In [27]:
sg=dgl.node_subgraph(g,torch.nonzero(g.ndata['obj']).squeeze())
pred=conv(sg,sg.ndata['f'])

In [28]:
print(pred.shape)

torch.Size([3, 20])
