In [6]:
import numpy as np
import math

In [2]:
dec=np.array(([[1,2,3],[4,5,6],[7,8,9]]))

In [3]:
print(dec)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
vec=np.linalg.norm(dec,2,axis=1)
print(vec)

[ 3.74165739  8.77496439 13.92838828]


In [8]:
print(math.sqrt(49+64+81))

13.92838827718412
